### PR TITLE
new dockerfile

### PR DESCRIPTION
**Pull request by fneu**
coala: everything passing
coala-bears: 8 failed, 326 passed, 1 pytest-warnings in 123.09 seconds

### CODE REVIEW

**Comment by fneu** [comment]
let's see what gives, 8 failures to go

this can be split into proper commits once we are where we need to be.

I would be thankful for advice on the remaining failures.

**Comment by fneu** [comment]
CC @AbdealiJK @sils1297

**Comment by AbdealiLoKo** [comment]
**CSSAutoPrefixBear** : When I try runnning the postcss command it mentions locally, I find that the result is supposed to be there. `display: -webkit-flex;` line is removed. Maybe this depends on the autoprefixer version ?

I'm using autoprefixer v6.3.6 and postcss-cli v2.5.2

**Comment by AbdealiLoKo** [comment]
**LatexLintBear**: This seems like a bug in coala. Essentially, the `subprocess` command must be converting the output from the program into the system's encoding. In the docker, the encoding is not UTF-8, while most of our systems must have utf-8. Which would cause a UnicodeDecodeError. We need to handle the decoding of the output properly.

**Comment by AbdealiLoKo** [comment]
**ProseLintBear** - Check the version of nodejs. ProseLint has issues with older versions from what I remember. We test it using nodejs 4.x+ iirc

**Comment by AbdealiLoKo** [comment]
**VerilogLintBearTest** `OSError: [Errno 8] Exec format error` normally occurs if the file youre tryin to run is non-executable - Reference: http://stackoverflow.com/questions/26807937/subprocess-popen-oserror-errno-8-exec-format-error-in-python

**Comment by sils** [comment]
@fneu how's this going? ETA? Help needed?

**Comment by fneu** [comment]
need to speak to my prof tomorrow to plan out times and stuff. If somebody would build this locally and try to verify Abdealis ideas (and maybe fix them) that would sure be nice.

**Comment by AbdealiLoKo** [comment]
I tried building it locally 2 days ago. After my computer doing stuff for nearly 4 hours, I had to end it because it was taking too long ... Then I had half finished images which I wasn't able to continue for some reason ...
I don't have the processing time to spare for this right now though. So, just a warning for anyone trying to build it locally .. takes a lot of time and ~5gb of space.

**Comment by fneu** [comment]
Yeah I know, also watch out for disk space guys, docker can really f*ck up a system if you let it consume all of the remaining disk space. I tried.

**Comment by fneu** [comment]
**CSSAutoPrefixBear:**

> I'm using autoprefixer v6.3.6 and postcss-cli v2.5.2

autoprefixer v6.3.7 and postcss-cli v2.5.2

**ProseLintBear**

> nodejs 4.x+ iirc

uhm... nodejs 6.2.1 on docker, same for npm

**VerilogLintBear**

verilator is up and running fine, the error should be manually reproducible though, will try later

**LatexLintBear** 

filed as https://github.com/coala-analyzer/coala/issues/2426

**Comment by fneu** [comment]
So I didn't have too much time today besides checking those things out. Generally I am hoping to fix CSSAutoPrefixBear and ProseLintBear in the following days and then make this mergeable.

LatexLintBear and VerilogLintBear don't seem too important for me, they can probably be manually removed for now and then added in a later PR.

**Comment by underyx** [comment]
Could this get merged in its current state? I see no reason why the remaining bears couldn't be added/fixed in a later commit, and the work here would be immensely useful, since it's a huge improvement over the current master.

Can anyone think of any downsides for merging as it is now?

**Comment by fneu** [comment]
@underyx this is already merged on `master` and `pre` branches for this very reason!

**Comment by underyx** [comment]
@fnue oh, so is it just not published on Docker Hub? Because I'm getting

```
[ERROR][22:30:28] NLTK data missing, install by running following commands `python3 -m nltk.downloader punkt maxent_treebank_pos_tagger averaged_perceptron_tagger`
```

with a freshly pulled `coala/base` image for `GitCommitBear`. It looks like this PR was supposed to fix that.

**Comment by fneu** [comment]
Weird since I rebuild the docker images after pushing. I will check today.

Am 23. Juli 2016 12:31:36 vorm. schrieb Bence Nagy notifications@github.com:

**Comment by underyx** [comment]
@fneu did you end up figuring out what's wrong? :/

**Pull request closed without merging**
