### PR TITLE
DockerFile: Changed cache NLTK data to  one command

### PR DESCRIPTION
**Pull request by namanyadav12**
Cache NLTK data in a single command instead of three different commands.
Closes https://github.com/coala/docker-coala-base/issues/34

### CODE REVIEW

**Review by jayvdb — APPROVED** [review]

**Comment by Nosferatul** [comment]
Please follow coala.io/commit, add `Closes <linktoyourissue>`, use `git commit --amend` -> change commit message -> push force again. Also next time, don't work on the master branch, make a branch and work there

**Comment by namanyadav12** [comment]
OK. Made the changes.

**Comment by aptrishu** [comment]
ack a10c942

**Comment by Mixih** [comment]
@rultor merge

**Pull request merged**
