### PR TITLE
Remove rultor and update maintainer

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Review by li-boxuan — COMMENTED** [review]
Hey, why is commit e6988c9 (Dockerfile: Change maintainer) in this PR? I think it should be in another PR.

**Comment by Makman2** [comment]
They are separate issues, and I just thought I fix it here in one go.

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
ack https://github.com/coala/docker-coala-base/pull/252/commits/570f303b919a910b2dc197f010a37a23159243de https://github.com/coala/docker-coala-base/pull/252/commits/e6988c92117c292e96f0724fa13fd8d5cbdf337c

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
