### PR TITLE
Remove unused Python 2 dependencies

### PR DESCRIPTION
**Pull request by jayvdb**
Removes zypper packages:

- python2-packaging
- python2-Pygments
- python2-pyparsing
- python2-setuptools

Related to https://github.com/coala/docker-coala-base/issues/83
Related to https://github.com/coala/docker-coala-base/issues/55

### CODE REVIEW

**Comment by jayvdb** [comment]
This has almost zero impact on image size, so it is only beneficial for tracking unused packages (and ensuring they dont become used by a new bear linter).

**Review by yash-nisar — APPROVED** [review]
LGTM

**Comment by yash-nisar** [comment]
ack 38872a210f6b52bd12d14f24b792337d64fc944e

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
