### PR TITLE
Use Gemfile from coala-bears

### PR DESCRIPTION
**Pull request by jayvdb**
Fixes https://github.com/coala/docker-coala-base/issues/27

### CODE REVIEW

**Comment by Nosferatul** [comment]
ack 963bc11

**Comment by jayvdb** [comment]
Hold! The Gems are working, but the npm packages are not being found.

**Comment by jayvdb** [comment]
unack 963bc11

**Comment by AbdealiLoKo** [comment]
Can this be closed in favor of https://github.com/coala/docker-coala-base/pull/44 ?

**Comment by Mixih** [comment]
ack a2522a7

**Pull request merged**
