### PR TITLE
Add dependency `phpmd` for PHPMessDetectorBear

### PR DESCRIPTION
**Pull request by yash-nisar**

### CODE REVIEW

**Comment by jayvdb** [comment]
Why not use https://software.opensuse.org/package/phpmd ?

**Comment by jayvdb** [comment]
Ugh. It is v2.3.2 (Release date 2015/09/24) while the latest is v2.6.0.  See [releases](https://phpmd.org/download/release/archive.html)

**Comment by SanketDG** [comment]
What's wrong with doing `composer install phpmd/phpmd`, composer is pretty stable.

**Comment by jayvdb** [comment]
> What's wrong with doing composer install phpmd/phpmd, composer is pretty stable.

Good idea.  [`php-composer`](https://software.opensuse.org/package/php-composer) is an official openSUSE package for Tumbleweed, so this should be easy.

**Pull request closed without merging**
