### PR TITLE
Remove unnecessary Python 2.7 files

### PR DESCRIPTION
**Pull request by jayvdb**
Also test subversion, bzr and mecurial.
And remove unncessary subversion files.

Related to https://github.com/coala/docker-coala-base/issues/83

### CODE REVIEW

**Comment by jayvdb** [comment]
Reduces image by 25Mb

**Comment by fneu** [comment]
ack https://github.com/coala/docker-coala-base/pull/122/commits/6afbcd760b395275c018013a84002614bdcad3ea

**Comment by fneu** [comment]
@jayvdb sorry i kinda messed up thinking I was on gitlab. Do you mind removing the merge commit and rebasing? Looks good besides.

**Comment by jayvdb** [comment]
reack cee2808

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
