### PR TITLE
Remove systemd packages

### PR DESCRIPTION
**Pull request by jayvdb**
Also remove dependency `kbd` which is not part of the base image.

### CODE REVIEW

**Comment by yukiisbored** [comment]
ack https://github.com/coala/docker-coala-base/pull/104/commits/5a2f975261446a59a2211b0d064c9b153ea22570

**Comment by Udayan12167** [comment]
@rultor merge

**Comment by jayvdb** [comment]
reack 0803abf

**Comment by jayvdb** [comment]
reack 4ff7ba4

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
