### PR TITLE
April 2017 fixes

### PR DESCRIPTION
**Pull request by jayvdb**
- Fix package selection based on upstream package changes (#155 and #156)
- Workaround https://github.com/coala/docker-coala-base/issues/157 which is an old ERROR that is now exit code 1

### CODE REVIEW

**Review by underyx — APPROVED** [review]
I assume rpm has no equivalent of `apt-get autoremove` then :(

**Comment by yukiisbored** [comment]
ack https://github.com/coala/docker-coala-base/pull/158/commits/bb18f32cda5067082d48c101b5f0451c06695474

**Comment by yukiisbored** [comment]
ack https://github.com/coala/docker-coala-base/pull/158/commits/0d60ce88e5b5e788a1c7351acc0d41be5e3f81fd

**Comment by yukiisbored** [comment]
ack https://github.com/coala/docker-coala-base/pull/158/commits/b7d4f3857dac42d9002aefc73e269753c437c19f

**Review by yukiisbored — APPROVED** [review]

**Comment by jayvdb** [comment]
@underyx, this is doing the opposite of `autoremove` if I am remembering correctly.
It is removing rpm's which are listed as mandatory dependencies when they are, in fact, not mandatory at least for our use case.  We've removed .5 Gb, mostly using this method.  If you know a better/less-churn way to achieve this, I'd love to see it.
Our base Tumbleweed is by definition in flux.  And it doesnt help that a few openSUSE packagers have looked at this Dockerfile, so they are naturally fixing the unnecessary dependencies, and adding missing dependencies.

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
