### PR TITLE
README.md: Replace coala-analyzer to coala

### PR DESCRIPTION
**Pull request by etotientz**
Closes https://github.com/coala/docker-coala-base/issues/92

### CODE REVIEW

**Review by damngamerz — COMMENTED** [review]
ack 47be0d30910cecd3de05721b3c5aae6c0c8b84cd
seems fine to me :+1:

**Comment by sims1253** [comment]
same here. you already have a newcommer issue fixed. please move on do difficulty/low

**Comment by sims1253** [comment]
As it says in the newcomer guide, if you've already solved one newcomer issue, you can't solve this and should move on to a low issue. So we'll be closing this - if you disagree, let us know

**Comment by etotientz** [comment]
ok

**Pull request closed without merging**
