### PR TITLE
Removes dbus

### PR DESCRIPTION
**Pull request by jayvdb**
Fixes https://github.com/coala/coala/issues/2949

### CODE REVIEW

**Comment by sils** [comment]
not sure if this should go to master or to pre? where do we now maintain the files properly?

**Comment by sils** [comment]
ok the master branch is `latest`, maybe we should point latest to the latest release branch and use master instead of pre so we can do stuff like this which is related to the prerelease

**Comment by sils** [comment]
ok declaring this WIP because we shouldn't merge this onto master unless we have the coala 0.9 image on master. Ideally we shift the latest tag to the latest release and maintain the prerelease on master so changes like this are possible in the future.

**Comment by jayvdb** [comment]
Im very happy if someone could rebase and merge. Im on mobile.

**Comment by Mixih** [comment]
Waiting on backport or point release in coala to fix errors.

**Comment by sils** [comment]
We already cherry picked that on @underyx ' branch.

**Comment by sils** [comment]
this commit was merged into master as part of another PR

**Pull request closed without merging**
