### PR TITLE
.travis.yml: Unhide the image size

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by adtac** [comment]
ack https://github.com/coala/docker-coala-base/pull/150/commits/c069885ccef5d9fcd518ffaf46ed3ae8cc92f389

**Comment by adtac** [comment]
@cherry-pick-bot

**Comment by adtac** [comment]
@rultor merge

**Comment by adtac** [comment]
@rultor stop

**Comment by jayvdb** [comment]
reack 8f85c29

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
