### PR TITLE
Add dependency `astyle`

### PR DESCRIPTION
**Pull request by yash-nisar**
Closes https://github.com/coala/docker-coala-base/issues/213

### CODE REVIEW

**Comment by yash-nisar** [comment]
CC @Makman2

**Comment by yash-nisar** [comment]
Docker is red, see [this build](https://travis-ci.org/yash-nisar/docker-coala-base/builds/256085447), which is the latest build **without my commit**.

**Comment by Makman2** [comment]
Looks good to me

**Comment by Makman2** [comment]
ack ee1fbda

**Comment by Makman2** [comment]
CC @jayvdb our docker expert :)

**Pull request merged**
