### PR TITLE
Mention relevant section of user manual

### LINKED ISSUE #15: Quick start for using as a Travis job
It would be useful to provide a recipe for users to copy and paste into their `.travis.yml` to use this docker as a linter job, and possibly also for other CI engines that support dockers.

It should use auto-discovery as much as possible, so that the sample recipe works irrespective of the contents of the repository, and only needs to be tuned if the code is buggy, or they want to reduce the runtime by focusing coala on specific areas of the repo or types of files..

This may already exist in the documentation, in which case a link in this repos `README.md` would be sufficient.

We could go one step further and build a tool that automatically creates the `.travis.yml`, etc.

### PR DESCRIPTION
**Pull request by jayvdb**
Fixes #15

### CODE REVIEW

**Comment by jayvdb** [comment]
This depends on https://github.com/coala-analyzer/documentation/pull/100

**Comment by sils** [comment]
LGTM, @fneu is the build thing normally failing?

**Comment by sils** [comment]
It looks like the travis CI for this image isn't fully done yet, @fneu was working on that, let's see what his plans are ;)

**Comment by fneu** [comment]
Yeah at one point we agreed to add a Travis check, but it fails because not all coala-bear pytests are passing and we proceeded because "good enough".

After my exam on Thursday I can try to Finish the Docker Image or comments out the bear-tests on Travis, the coala Tests themself should Pass.
After my exam on Thursday I might try to "Finish"

**Comment by fneu** [comment]
Coala is sufficiently tested and stable that you can consider it working if the Docker Image builds on docker Hub.

**Comment by sils** [comment]
@fneu the dependency of this PR has been merged, feel free to merge this. Do you have a merge policy for this repo yet? Might wanna set up rultor or so.

**Pull request merged**
