### PR TITLE
coafile: Add commit message checking

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by sils** [comment]
@fneu I activated gitmate for your repo - hope you don't mind

**Comment by sims1253** [comment]
has the ci been fixed?

**Comment by sils** [comment]
no it's ATM an expected failure I think, CC @fneu who wanted to look into PRs for this repo anyway

**Comment by fneu** [comment]
@sims1253 the ci has been fixed since a while but this PR is not rebased I believe.

Since this PR doesn't touch `.travis.yml` it's not a problem though

**Pull request merged**
