### PR TITLE
Dockerfile: Clear /tmp after each command

### PR DESCRIPTION
**Pull request by jayvdb**
Saves 5Mb

### CODE REVIEW

**Comment by fneu** [comment]
this doesn't look like the best way to do things :/

**Comment by jayvdb** [comment]
@fneu , could you expand your comment. e.g. Is there a better way?  If so, what?

**Comment by fneu** [comment]
There probably isn't a better way because of the layered nature of Docker, right? To remove everything in `/tmp` at once we'd need to run every command at once, which probably would save a ton of space but is probably not a good idea.

I just meant this looks really ugly, since you seem to really need the free space, feel free to go ahead with it.

**Comment by jayvdb** [comment]
I can store the command in a bash script, which makes it easier (and neater) to append to each RUN command.

**Comment by fneu** [comment]
might be nicer although in the end it's the same thing so you might as well leave the commands in.

btw. I just found [this](https://developers.redhat.com/blog/2016/03/09/more-about-docker-images-size/) blog post talking about docker image sizes. It looks like each layer adds significant amount of required space, and we have a ton of them. Have you ever thought about moving all of the installation steps out into a single bash script?

Tbh. I have no idea what we would win or lose besides every build of the image taking an hour, but if space is a problem that might be worth it?

**Comment by jayvdb** [comment]
We have https://github.com/coala/docker-coala-base/issues/59 about image layers.
(we've removed many of the layers, and more reduction needed).

**Comment by fneu** [comment]
ack https://github.com/coala/docker-coala-base/pull/119/commits/46a0820de71ada2c57130d5b9dd19c2483586c01

**Comment by fneu** [comment]
@rultor merge

**Comment by fneu** [comment]
@jayvdb feel free to merge this after a rebase

**Comment by jayvdb** [comment]
reack ae9479b

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
