### PR TITLE
Update Dockerfile to have coala 0.9

### PR DESCRIPTION
**Pull request by underyx**

### CODE REVIEW

**Comment by sils** [comment]
ack https://github.com/coala/docker-coala-base/pull/36/commits/954aea6a4fb7ca4f8335ea11cc0f7ae13aeab2d1

**Comment by sils** [comment]
can you cherry pick https://github.com/coala/docker-coala-base/pull/30/commits/04992dddf26b6c8f819fc6c5cd95b54bc064dc1c ?

**Comment by underyx** [comment]
@sils done

**Comment by Mixih** [comment]
Waiting on backports and possible point release

**Comment by sils** [comment]
I just consulted @fneu about this, I hereby vote for merging this despite the build failure so we can get the 0.9 docker image ASAP. Also we should make the 0.9 branch. Then we fix the build by making the next coala bugfix release etc. but those build failures don't seem to be affecting the user at all

**Comment by sils** [comment]
@fneu agrees

**Comment by sils** [comment]
getting this to master so we have a working pre

**Pull request merged**
