### PR TITLE
Dockerfile: Remove bl.tar.gz after installation

### PR DESCRIPTION
**Pull request by gaocegege**
To reduce the size of coala/base image

Signed-off-by: Ce Gao <ce.gao@outlook.com>

### CODE REVIEW

**Comment by jayvdb** [comment]
I think ..
 Untested ...
A better way of doing it is to write the tgz to /tmp.

**Comment by gaocegege** [comment]
I find docker official libraries use this way:

[docker-library/docker](https://github.com/docker-library/docker/blob/05678f7f3198d0787d78de9bdc084dcffccf7276/1.12/Dockerfile#L13:#L19)
[docker-library/julia](https://github.com/docker-library/julia/blob/7e52c3cd99d1b39028bf4b36da493ec47cb643c2/Dockerfile#L12:#L21)

:thinking:

**Comment by jayvdb** [comment]
ack 2592c76

**Comment by jayvdb** [comment]
reack 923be9c

**Comment by jayvdb** [comment]
Try another force push?

**Comment by gaocegege** [comment]
Yeah

**Comment by gaocegege** [comment]
reack 89d05c3

**Comment by jayvdb** [comment]
@rutlor merge

**Comment by jayvdb** [comment]
@rultor merge

**Comment by gaocegege** [comment]
The PR needs a manual review, my reack doesn't works :man:

**Comment by jayvdb** [comment]
ack 89d05c3

**Comment by jayvdb** [comment]
@rultor merge

**Comment by jayvdb** [comment]
> A better way of doing it is to write the tgz to /tmp.

I was wrong.  `/tmp` isnt automatically cleaned by Docker.
So there are small savings in cleaning it after each command: https://github.com/coala/docker-coala-base/pull/119

**Pull request merged**
