### PR TITLE
Remove unused packages

### PR DESCRIPTION
**Pull request by jayvdb**
Also mention why some packages are needed.

Related to https://github.com/coala/docker-coala-base/issues/55

### CODE REVIEW

**Comment by Nosferatul** [comment]
ack 3975894

**Comment by Nosferatul** [comment]
rebase needed

**Comment by jayvdb** [comment]
reack 889f0c8

**Comment by jayvdb** [comment]
@rultor merge

**Comment by jayvdb** [comment]
reack 889f0c8

**Comment by Nosferatul** [comment]
reack 889f0c8

**Comment by jayvdb** [comment]
reack fb22edf

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
