### PR TITLE
Pin lua and use zypper install --replacefiles

### PR DESCRIPTION
**Pull request by jayvdb**
Fixes https://github.com/coala/docker-coala-base/issues/210 and https://github.com/coala/docker-coala-base/issues/211 .

### CODE REVIEW

**Comment by jayvdb** [comment]
Note that a viable alternative to using `--replacefiles` is explicitly upgrading `kmod-compat`, which will likely add only a tiny bit to the image size.  But then that needs to be reverted once upstream fixes their problem.  `--replacefiles` shouldnt cause any problems -- if it does, the problems should cause a failure in our tests.

**Comment by jayvdb** [comment]
Note the travis tests on https://github.com/coala/docker-coala-base/pull/206 passed, which is built on top of this PR, so we dont need to rerun Travis on this PR (please dont restart it! it is evidence of a timeout).

As a result, I've made the Docker Cloud CI mandatory instead of Travis CI mandatory, so that this can be merged now.

And https://travis-ci.org/jayvdb/docker-coala-base/builds/253819953 is 114e179 built on my fork, also green.

**Comment by yukiisbored** [comment]
ack https://github.com/coala/docker-coala-base/pull/151/commits/b5eddaa4239da836b22719901c23bf3b4b6eb025

**Comment by yukiisbored** [comment]
ack https://github.com/coala/docker-coala-base/pull/151/commits/114e179b3f788333f2944b2668f77d11674dbfe8

**Comment by yukiisbored** [comment]
@rultor merge

**Pull request merged**
