### PR TITLE
Verify rpm.install.excludedocs = yes

### PR DESCRIPTION
**Pull request by jayvdb**
Sanity check.
If this flag changes, the size of the image radically increases.

### CODE REVIEW

**Comment by Nosferatul** [comment]
@jayvdb could you rebase?

**Comment by Nosferatul** [comment]
ack b7283f6

**Comment by sils** [comment]
reack https://github.com/coala/docker-coala-base/pull/148/commits/ecd5bb4ccbbf95d812cf365b923d8c2e0093c329

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
