### PR TITLE
.coafile: Sync .coafile shortlog_regex

### PR DESCRIPTION
**Pull request by jayvdb**
Import .coafile shortlog_regex from coala/coala

Fixes https://github.com/coala/docker-coala-base/issues/228

### CODE REVIEW

**Comment by adtac** [comment]
ack https://github.com/coala/docker-coala-base/pull/229/commits/c24a666f2d2655e94c31f90b44cdfd1dfb5598a6

**Comment by guyzmo** [comment]
@rultor merge

**Comment by jayvdb** [comment]
yay "@guyzmo is not in the maintainers group."

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
